name: medical_records_mobile
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.0
  hexcolor: ^3.0.1
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  # dropdown_textfield: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/